### ISSUE TITLE
Add link for installation to the Readme landing page

### ISSUE THREAD

**Issue by kristiank** [GIRA/PhysicalBits#37]
Right now it is confusing to land on Physical Bits github page if you come there with the intention to install and try out the software. It would be good to link to instructions how you get the environment running (not necessarily how to get the firmware installed). Maybe it would make sense to host the latest release somewhere online? This way people could very easily get an impression of the environment, see the blocks, see the different panes and options for language etc.

I am planning to do a campaign about the software in the relevant circles in Estonia, both for simply advertising the Physical Bits environment and also to ask for help proof-checking translations. Do you plan any new release in the near future?

**Comment by RichoM** [comment]
> Right now it is confusing to land on Physical Bits github page if you come there with the intention to install and try out the software. It would be good to link to instructions how you get the environment running (not necessarily how to get the firmware installed). 

Do you mean these instructions: https://gira.github.io/PhysicalBits/DOWNLOAD.html ?
I thought they were good enough but I'm probably biased :)
What do you suggest to make the instructions more explicit? Maybe adding some screenshots would help?

Or do you mean the main [README](https://github.com/GIRA/PhysicalBits/blob/master/README.md)?
I kind of moved everything to the [website](https://gira.github.io/PhysicalBits/) now so maybe I should add something like a table of contents here with a few links to important places (specially to the download page).

> Maybe it would make sense to host the latest release somewhere online? This way people could very easily get an impression of the environment, see the blocks, see the different panes and options for language etc.

Yes! That is a very good idea. I would have to refactor the code a little bit to make the GUI more independent from the server, though. But that is something I want to do anyway so it's aligned with my plans.
In the long run I would love to have a fully online IDE that doesn't require installing anything (or maybe installing some small executable, kind of like the [Arduino plugin](https://create.arduino.cc/getting-started/plugin/welcome)).
I'm working on moving some of the compiler stuff to the client side (you can see my experiments in the [cljs-compiler](https://github.com/GIRA/PhysicalBits/tree/cljs-compiler) branch), but that will probably take some time.
 
> I am planning to do a campaign about the software in the relevant circles in Estonia, both for simply advertising the Physical Bits environment and also to ask for help proof-checking translations. Do you plan any new release in the near future?

That would be great! I want more people to know about the project. That's why I've been working on the website. I still haven't finished, though. The "about us" page is still empty. I want to write something about the team behind this project. And if it's okay with you, I would like to mention you and your contribution.

I'm not planning on a new release in the __near__ future. Except to fix a bug we may find. I would like to focus on refactoring the GUI code (which is a mess right now) and optimizing the compiler and virtual machine so that we can support bigger and more interesting programs. I have a lot of ideas for this but, as always, ideas are not good enough if I don't have the time to implement them.

BTW, I saw that some other open source projects are using discord to build a community. I'm not very familiar with it but do you think it would be a good idea to set up something like that?

Thanks!

**Comment by kristiank** [comment]
> > Right now it is confusing to land on Physical Bits github page if you come there with the intention to install and try out the software. It would be good to link to instructions how you get the environment running (not necessarily how to get the firmware installed).
> 
> Do you mean these instructions: https://gira.github.io/PhysicalBits/DOWNLOAD.html ?
> I thought they were good enough but I'm probably biased :)
> What do you suggest to make the instructions more explicit? Maybe adding some screenshots would help?
> 
> Or do you mean the main [README](https://github.com/GIRA/PhysicalBits/blob/master/README.md)?
> I kind of moved everything to the [website](https://gira.github.io/PhysicalBits/) now so maybe I should add something like a table of contents here with a few links to important places (specially to the download page).
> 

Yes, I wanted a direct link to the download page, your changes are great. Now for some more cosmetic and subjective proposals, I think it would be appropriate to:

  * Change the name of `Download` to maybe `Getting started`
  * Reorder the information on the Getting started (i.e. Download) page:
    * Keep as first the "Download" section, but here it would be appropriate to add an introduction text that Physical Bits can be downloaded either as a web application and be used in the browser, or download it as a standalone program (with links to the corresponding Starting as .... -subsections below).
    * Next I would put the Starting the software section (maybe renaming it to Starting Physical Bits)
      * Starting as a web application
         This is fine and I would keep it the same way as it is (only rename it "Web" -> "Starting as a web applllication".
      * Starting as standalone program
         Here also rename the section it to something more verbose, like "Desktop" -> "Starting as desktop program" (or standalone program). But, here I get confused what is meant as "the zip file". Maybe simply add a few words, like "First, extract the the contents of the _downloaded Windows or Mac OS_ zip file into a folder of your preference.
    * Installing the firmware
      Here I would move the "Installing Java" section to the bottom and rename the section to "Prerequisites". And thus have only the information about installing the firmware, which I think is great as it is, it tells you everything already, e.g. "In order for Physical Bits to connect to your Arduino board [...]".

What I think is important in the above reording of the information is that the user first wants to start the "GUI" part of Physical Bits and try dragging around some blocks etc, and only afterwards, as the next step comes the Firmware installation. I fear that too many would get a little scared with the words like "firmware" and changes to the Arduino. I really believe the first step is to familiarize the user with the GUI of Physical Bits, e.g. either as a web application or the desktop edition of it.


> > I am planning to do a campaign about the software in the relevant circles in Estonia, both for simply advertising the Physical Bits environment and also to ask for help proof-checking translations. Do you plan any new release in the near future?
> 
> That would be great! I want more people to know about the project. That's why I've been working on the website. I still haven't finished, though. The "about us" page is still empty. I want to write something about the team behind this project. And if it's okay with you, I would like to mention you and your contribution.
> 

I'm humbled by this. Ofcourse you can mention me!

> I'm not planning on a new release in the **near** future. Except to fix a bug we may find. I would like to focus on refactoring the GUI code (which is a mess right now) and optimizing the compiler and virtual machine so that we can support bigger and more 
interesting programs. I have a lot of ideas for this but, as always, ideas are not good enough if I don't have the time to implement them.
> 

Its okay, I'll just tweak my local code (which concerns only translations anyway).

> BTW, I saw that some other open source projects are using discord to build a community. I'm not very familiar with it but do you think it would be a good idea to set up something like that?
> 

Building a community is very important, but also I have no real experience about it. I can try take a look on Discord and generate some ideas. Can you maybe email me or write here some links to communities you are aware of?

One thing I have been thinking about is to try to join forces with the [Totem Maker](http://totemmaker.net/) people. For me this seems straight forward, as I have chosen to use their maker platform and they are situated near to Estonia (they are in Lithuania). Maybe they are interested in having their own programming platform... but this is probably a very cumbersome topic as it is directly connected to business and I am not really a business person, as you have noticed, I do things I love for free. But I wanted to mention the idea to you.

**Comment by RichoM** [comment]
Thanks for the suggestions on how to reorganize the "Download" page. I think you're right about the order of the sections. Although I think I would like to separate the web and desktop versions in different pages because now it looks confusing. 

Also, I'm working on bundling java in the download so for the next release we'll be able to remove that whole section and make the installation easier.

I'm not sure about renaming the "DOWNLOAD" button, though. Maybe something like "Get Physical Bits!" would be better?

> Building a community is very important, but also I have no real experience about it. I can try take a look on Discord and generate some ideas. Can you maybe email me or write here some links to communities you are aware of?

The discord server that caught my attention is this one for the [Godot Engine](https://discord.gg/4JBkykG). Anyway, it's probably too soon to be thinking about this, though. Maybe if someday the project gets more attention we can revisit this idea :)

> (...) this is probably a very cumbersome topic as it is directly connected to business and I am not really a business person

Thanks for the idea, but yes, I'm also not a business person. All I want is to have fun programming interesting stuff.

**Comment by RichoM** [comment]
Today I published a new release that fixes a couple of bugs and I updated the website.
I separated the download pages for the web and standalone versions (by the way, I like "standalone" much better than "desktop", thanks).
