### ISSUE TITLE
The application is still trying to open the port

### ISSUE THREAD

**Issue by jennifferch** [GIRA/PhysicalBits#40]
I have this message:

Conectando por serie.....
Abriendo puerto: COM3 

but it never shows me an error message or a success message.

**Comment by RichoM** [comment]
This sucks. After a lot of testing we discover that this error happens when the [Visual C++ 2010 Redistributable Package (x64)](https://www.microsoft.com/en-US/download/details.aspx?id=14632) is not installed (as mentioned [here](https://github.com/java-native-access/jna/issues/725#issuecomment-260422262)).

From what I read, it looks like newer versions of JNA don't have this issue. I don't know if we can update it, though. I'll look into that. For now, I think I'll add a "Troubleshooting" page describing this problem and how to solve it.
